### ISSUE TITLE
many js files can't get loaded

### ISSUE THREAD

**Issue by roman204** [Goomento/PageBuilder#27] opened 2023-04-02 12:49 UTC
Hi, currently there are some 404's 
![image](https://user-images.githubusercontent.com/584168/229353563-fad13bc3-4f35-4028-8645-1e7fb173fcae.png)

No only in my installation also in your demo.
https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.5/lib/oop.js
...
your demo is working but on my installation it doesn't load the pagebuilder.

**Comment by haihv433** [comment] 2023-04-03 04:08
Hi @roman204 

We knew this issue, these files are loading ACE editor from CDN, occurs if you didn't enable cache in browser. 
And since we detached this loading out of builder js, so it can not be the cause for preventing your builder being loaded, 

 we suspect other issues, can we have a look on your instance for more detail?

**Comment by roman204** [comment] 2023-04-03 05:50
Hy it was a local environment. But doesn't matter anymore. I cant use goomento for this project because it's not compatible with hyva or in other words it requires require.js and all the other js stuff luma is built with, and hyva removes that js bloat. So those two things are not compatible together.

**Comment by haihv433** [comment] 2023-04-06 09:49
Hi @roman204 
This module does not support Hyva theme so far, we afraid we do no more on your issue.

We close this issue for now, fell free to reopen this if have any concern. Thanks

**Closed by haihv433** 2023-04-06 09:49 UTC

**Comment by roman204** [comment] 2023-04-06 13:50
@haihv433 hopefully you can remove the dependencies from requirejs and luma. This module is a really a good idea and would be a great benefit for the magento ecosystem.
